#!/bin/sh -e

# change to sources list sid
>/etc/apt/sources.list cat - <<EOM
deb http://deb.debian.org/debian/ sid main contrib non-free
deb-src http://deb.debian.org/debian/ sid main contrib non-free
EOM

# upgrade to sid

apt-get update && apt-get full-upgrade

# gnome-wipe
apt-get purge epiphany seahorse totem rhythmbox evince gnome-software gnome-calculator software-properties-gtk firefox-esr gnome-system-monitor gnome-maps gnome-weather gnome-contacts gnome-clocks gnome-calendar gedit simple-scan gnome-font-viewer gnome-disk-utility gnome-connections gnome-logs eog baobab neovim cheese gnome-games gnome-sound-recorder im-config evolution synaptic shotwell gnome-todo transmission-gtk gnome-characters gnome-music malcontent file-roller gnome-documents && apt-get autoremove && apt-get upgrade && apt-get update

# enable 32-bit
dpkg --add-architecture i386 && apt-get update && apt-get upgrade

# Install needed applications
apt-get install micro htop xserver-xorg-core firefox power-profiles-daemon flatpak

# flatpak & discord; comment if needed
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo && flatpak install flathub com.discordapp.Discord

# save wanted (Add your wanted here)
apt-get install gnome-chess aisleriot quadrapassel

# remove yelp, reinstalls self on any gnome app
apt-get purge yelp

# purge Extra
# apt-get purge

# reboot
reboot

