#!/bin/sh -e

# Change to SID
rm /etc/apt/sources.list && echo "deb http://deb.debian.org/debian/ sid main contrib non-free
deb-src http://deb.debian.org/debian/ sid main contrib non-free" > /etc/apt/sources.list && apt-get update && apt-get full-upgrade

# Gnome-Wipe
apt-get purge seahorse totem rhythmbox evince gnome-software gnome-calculator software-properties-gtk firefox-esr gnome-system-monitor gnome-maps gnome-weather gnome-contacts gnome-clocks gnome-calendar gedit simple-scan gnome-font-viewer gnome-disk-utility gnome-connections gnome-logs eog baobab neovim cheese gnome-games gnome-sound-recorder im-config evolution synaptic shotwell gnome-todo transmission-gtk gnome-characters gnome-music malcontent file-roller gnome-documents && apt-get autoremove && apt-get upgrade && apt-get update

# Enable 32-bit
dpkg --add-architecture i386 && apt-get update && apt-get upgrade

# Install needed applications
apt-get install micro htop xserver-xorg-core firefox power-profiles-daemon flatpak

# Flatpak & Discord; Comment if needed
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo && flatpak install flathub com.discordapp.Discord

# Save wanted (Add your wanted here)
apt-get install gnome-chess aisleriot quadrapassel

# Remove yelp, reinstalls self on any gnome app
apt-get purge yelp

# Purge Extra
# apt-get purge

# Reboot
reboot
